### ISSUE TITLE
Modularize project

### ISSUE THREAD

**Issue by anasabau** [anasabau/FlightManager#2]
Project should be split in more maven modules managed by a central pom.

**Comment by stoiandan** [comment]
_modularization_ branch created, looks ok but should be tested, after that will merge with _master_ branch

**Comment by stoiandan** [comment]
the end result should look similar to this:

- FlightManager central pom 
                -     api module, that exposes only some interfaces (entities and DAO interface here)
                -     business (ejbs that use the DAO, DAO implementation, services, persistence xml)
                -     JSF (.xhtml pages that make use of these @Stateless or @Statefull ejbs )
